### ISSUE TITLE
Hard coded path causing trouble on other systems.

### ISSUE THREAD

**Issue by yashbhutoria** [alfaijmansuri/python-tkinter#1]
https://github.com/alfaijmansuri/python-tkinter/blob/f4c7b922513cf557e90a5679858169430d4a9281/pythontkinter.py#L70

**Comment by yashbhutoria** [comment]
The issue is still there

**Comment by yashbhutoria** [comment]
why did you closed it ?

**Comment by alfaijmansuri** [comment]
sir modify kiya tha code .
